### ISSUE TITLE
oss.jsonについて（Golang）

### ISSUE THREAD

**Issue by 1-dim-torus-jp** [kaiy-jp/livepeer-org#15]
# Golangの訳し方について

https://livepeer-4khih3gxr-kaiwai.vercel.app/ja/oss

![image](https://user-images.githubusercontent.com/105644276/213913184-81f458eb-7e9b-426a-8d4c-1207115688bf.png)

細かいことで恐縮なのですが、画像内文章の中にある、Golangというのは、所謂Go言語のことだとおもうのですが、

このままGolang表記でいくか、それともGo言語と訳してしまうか？！

で迷っています。

どちらがより日本のユーザーにフレンドリーでしょうか？！

ご意見の程よろしくお願い致します。

**Comment by ikisuke** [comment]
Go言語の方が良いかなと思います(直感ですw)

**Comment by 1-dim-torus-jp** [comment]
@ikisuke さん
コメントありがとうございます！
やはりそうですよね、日本人が読むのだからGo言語の方が適当ですかね。
GitHub上直しておきます！！
（技術的な事をよく分かっていないためデプロイはまだできないので（イシューの修正片付いたらCieloさんにご教示いただく予定です。）、表面上の表示は直りませんがご承知おきください。）

**Comment by 1-dim-torus-jp** [comment]
GitHub上修正しました！！

こちらのissueはcloseとさせていただきます。
