### ISSUE TITLE
文言の確認

### ISSUE THREAD

**Issue by araimono** [kaiy-jp/livepeer-org#3]
https://github.com/kaiy-jp/livepeer-org/blob/feature/translate-into-JP/public/locales/ja/about.json
 
 # 意味が通っているか確認
 日本語として意味がとおっているか、推敲する!
 
 "page-about-mission-text-one": "オープンソースソフトウェアのパワーを活かし、コンピューティングや帯域幅といった十分に活用されていないリソースを活用し、ブートストラップや参加への暗号経済的なインセンティブを利用することで、ビデオストリーミングアプリケーションを高効率な価格で、かつ無限に拡張できるインフラを提供することができます。",
  
  # 意味が通っているか確認
  
  "page-about-mission-text-two": "高画質カメラの普及や帯域のユビキタス化とともに、従来の中央集権的なコスト構造では不可能だったビデオアプリケーションを実現し、これからの社会のコミュニケーション、経済的機会、エンターテインメントを開放していくと考えています。", //（←意味通っているか？）

**Comment by araimono** [comment]
日本語翻訳の画面イメージってこんな感じですね!
![image](https://user-images.githubusercontent.com/48848074/211160238-72d6abfa-91f2-4c23-865b-503b73868404.png)

原文は
![image](https://user-images.githubusercontent.com/48848074/211160279-68433d4f-3b7c-4206-bb0f-13c63aece99a.png)
こんなかんじです!

Through the power of open source software, the harnessing of underutilized resources like compute and bandwidth, and the use of cryptoeconomic incentives for bootstrapping and participation, there is an opportunity to deliver an infrastructure that can power video streaming applications at a highly efficient price, and infinite scale.

ちょっと、ためしに意訳してみました!
どうでしょう? 
@1-dim-torus-jp  @CieloChiara 

オープンソースソフトウェアのパワーを活かし、コンピューティングや帯域幅といった十分に活用されていないリソースを活用します。ビデオ配信インフラの構築に参加することをクリプトエコノミーのインセンティブを利用することで、ビデオストリーミングアプリケーションを高効率な価格で、かつ無限に拡張できるインフラを提供することができます。

**Comment by araimono** [comment]
ぜんぜんだめだとおもいます
やりなおし!

**Comment by araimono** [comment]
ひゃい!

**Comment by CieloChiara** [comment]
@araimono @1-dim-torus-jp @CieloChiara 
メンションテストです。

**Comment by CieloChiara** [comment]
@araimono @1-dim-torus-jp 
こちらメンションのテストです。

**Comment by araimono** [comment]
@1-dim-torus-jp 
@CieloChiara

**Comment by CieloChiara** [comment]
@1-dim-torus-jp @araimono
