### ISSUE TITLE
二重敬語について

### ISSUE THREAD

**Issue by 1-dim-torus-jp** [kaiy-jp/livepeer-org#9]
# 二重敬語について

common.json, resources.json, tokenholders.jsonに共通して存在する問題点なのですが、
（参考URL)
https://livepeer-4khih3gxr-kaiwai.vercel.app/ja/resources
https://livepeer-4khih3gxr-kaiwai.vercel.app/ja/tokenholders

![image](https://user-images.githubusercontent.com/105644276/213863462-3d702af7-4f88-4e0d-b3dd-0aeb63c2ed14.png)

FAQを、（よくある質問ではなく、）「よくあるご質問」と訳したいです。（企業のコーポレートサイトなどを見ているとその方がよさそう。）すると、「よくあるご質問をご覧ください。」の訳し方に困ってしまいます。「ご質問をご覧」は二重敬語になって逆におかしくないでしょうか？！（新卒時のの新人教育で、二重敬語は丁寧過ぎて逆に失礼に当たる、と習いました。）「よくあるご質問をご紹介します。」は、「よくあるご質問を紹介します。」にすればいいのですが。
気にしすぎでしょうか？！

**現時点でのとーらすの考え：**
「よくあるご質問」は堅持したいので、
「よくあるご質問をご覧ください。」はそのまま。（この程度の二重敬語は許容する。）
「よくあるご質問をご紹介します。」は「よくあるご質問を紹介します。」に。（ご紹介の方がいい？）

ご意見を拝聴したく。
よろしくお願い致します。

**Comment by araimono** [comment]
![image](https://user-images.githubusercontent.com/48848074/215673146-e7429b8f-0d82-4504-a37d-1238e07deb7f.png)

**Comment by 1-dim-torus-jp** [comment]
「よくあるご質問をご覧ください。」も「よくあるご質問をご紹介します。」もそのままで！

**Comment by araimono** [comment]
下記に統一

よくあるご質問をご覧ください。
よくあるご質問をご紹介します。
で統一する(JR、ゆうちょにならう)

フォーマルでとりあえず揃えておき、翻訳が完成したときに全体の雰囲気で再度調整する。

**Comment by 1-dim-torus-jp** [comment]
すみません、GitHub上への反映作業を完了するまでreopenさせてください。（作業進捗管理の為。）

**Comment by 1-dim-torus-jp** [comment]
GitHub上への反映作業完了しましたのでcloseします。
